// Generated by CoffeeScript 1.4.0
(function() {

  jQuery(function() {
    $.tags = function(element, options) {
      var _this = this;
      this.suggestions = options.suggestions;
      this.restrictTo = (options.restrictTo != null ? options.restrictTo.concat(this.suggestions) : false);
      this.tagsArray = [];
      this.tagData = "";
      this.$element = $(element);
      this.removeTagClicked = function(e) {
        if (e.currentTarget.tagName === "A") {
          _this.removeTag(e.currentTarget.previousSibling.textContent);
          return $(e.currentTarget.parentNode).remove();
        }
      };
      this.removeLastTag = function() {
        var el;
        el = $('.tag', _this.$element).last();
        el.remove();
        return _this.removeTag(_this.tagsArray[_this.tagsArray.length - 1]);
      };
      this.removeTag = function(tag) {
        _this.tagsArray.splice(_this.tagsArray.indexOf(tag), 1);
        _this.tagData = _this.tagsArray.join(',');
        return _this.renderTags(_this.tagsArray);
      };
      this.addTag = function(tag) {
        if ((_this.restrictTo === false || _this.restrictTo.indexOf(tag) !== -1) && _this.tagsArray.indexOf(tag) < 0) {
          _this.tagsArray.push(tag);
          _this.tagData = _this.tagsArray.join(',');
          return _this.renderTags(_this.tagsArray);
        }
      };
      this.toggleCloseColor = function(e) {
        var opacity, tagAnchor;
        tagAnchor = $(e.currentTarget);
        opacity = tagAnchor.css('opacity');
        opacity = (opacity < 0.8 ? 1.0 : 0.6);
        return tagAnchor.css({
          opacity: opacity
        });
      };
      this.keyDownHandler = function(e) {
        var k, numSuggestions, tag;
        k = (e.keyCode != null ? e.keyCode : e.which);
        switch (k) {
          case 13:
            tag = e.target.value;
            if (_this.suggestedIndex !== -1) {
              tag = _this.suggestionList[_this.suggestedIndex];
            }
            _this.addTag(tag);
            e.target.value = '';
            _this.renderTags(_this.tagsArray);
            return _this.hideSuggestions();
          case 46:
          case 8:
            if (e.target.value === '') {
              _this.removeLastTag();
            }
            if (e.target.value.length === 1) {
              return _this.hideSuggestions();
            }
            break;
          case 40:
            if (_this.input.val() === '' && (_this.suggestedIndex === -1 || !(_this.suggestedIndex != null))) {
              _this.makeSuggestions(e, true);
            }
            numSuggestions = _this.suggestionList.length;
            _this.suggestedIndex = (_this.suggestedIndex < numSuggestions - 1 ? _this.suggestedIndex + 1 : numSuggestions - 1);
            _this.selectSuggested(_this.suggestedIndex);
            return _this.scrollSuggested(_this.suggestedIndex);
          case 38:
            _this.suggestedIndex = (_this.suggestedIndex > 0 ? _this.suggestedIndex - 1 : 0);
            _this.selectSuggested(_this.suggestedIndex);
            return _this.scrollSuggested(_this.suggestedIndex);
          case 9:
          case 27:
            return _this.hideSuggestions();
        }
      };
      this.makeSuggestions = function(e, overrideLengthCheck) {
        var val;
        val = (e.target.value != null ? e.target.value : e.target.textContent);
        _this.suggestedIndex = -1;
        _this.$suggestionList.html('');
        _this.suggestionList = [];
        $.each(_this.suggestions, function(i, suggestion) {
          if (_this.tagData.indexOf(suggestion) < 0 && suggestion.substring(0, val.length) === val && (val.length > 0 || overrideLengthCheck)) {
            _this.$suggestionList.append('<li class="tags-suggestion">' + suggestion + '</li>');
            return _this.suggestionList.push(suggestion);
          }
        });
        $('.tags-suggestion', _this.$element).mouseover(_this.selectSuggestedMouseOver);
        $('.tags-suggestion', _this.$element).click(_this.suggestedClicked);
        if (_this.suggestionList.length > 0) {
          return _this.showSuggestions();
        } else {
          return _this.hideSuggestions();
        }
      };
      this.suggestedClicked = function(e) {
        var tag;
        tag = e.target.textContent;
        if (_this.suggestedIndex !== -1) {
          tag = _this.suggestionList[_this.suggestedIndex];
        }
        _this.addTag(tag);
        _this.input.val('');
        _this.makeSuggestions(e, false);
        _this.input.focus();
        return _this.hideSuggestions();
      };
      this.keyUpHandler = function(e) {
        var k;
        k = (e.keyCode != null ? e.keyCode : e.which);
        if (k !== 40 && k !== 38 && k !== 27) {
          return _this.makeSuggestions(e, false);
        }
      };
      this.hideSuggestions = function() {
        return $('.tags-suggestion-list', _this.$element).css({
          display: "none"
        });
      };
      this.showSuggestions = function() {
        return $('.tags-suggestion-list', _this.$element).css({
          display: "block"
        });
      };
      this.selectSuggestedMouseOver = function(e) {
        $('.tags-suggestion').removeClass('tags-suggestion-highlighted');
        $(e.target).addClass('tags-suggestion-highlighted');
        $(e.target).mouseout(_this.selectSuggestedMousedOut);
        return _this.suggestedIndex = $('.tags-suggestion', _this.$element).index($(e.target));
      };
      this.selectSuggestedMousedOut = function(e) {
        return $(e.target).removeClass('tags-suggestion-highlighted');
      };
      this.selectSuggested = function(i) {
        var tagElement;
        $('.tags-suggestion').removeClass('tags-suggestion-highlighted');
        tagElement = $('.tags-suggestion', _this.$element).eq(i);
        return tagElement.addClass('tags-suggestion-highlighted');
      };
      this.scrollSuggested = function(i) {
        var pos, tagElement, topElement;
        tagElement = $('.tags-suggestion', _this.$element).eq(i);
        topElement = $('.tags-suggestion', _this.$element).eq(0);
        pos = tagElement.position();
        return $('.tags-suggestion-list', _this.$element).scrollTop(tagElement.position().top - topElement.position().top);
      };
      this.adjustInputPosition = function() {
        var pBottom, pLeft, pTop, tagElement, tagPosition;
        tagElement = $('.tag', _this.$element).last();
        tagPosition = tagElement.position();
        pLeft = tagPosition != null ? tagPosition.left + tagElement.outerWidth(true) : 0;
        pTop = tagPosition != null ? tagPosition.top : 0;
        $('.tags-input', _this.$element).css({
          paddingLeft: pLeft,
          paddingTop: pTop
        });
        pBottom = tagPosition != null ? tagPosition.top + tagElement.outerHeight(true) : 22;
        return _this.$element.css({
          height: pBottom
        });
      };
      this.renderTags = function(tags) {
        var tagList;
        tagList = $('.tags', _this.$element);
        tagList.html('');
        $.each(tags, function(i, tag) {
          tag = $(_this.formatTag(i, tag));
          $('a', tag).click(_this.removeTagClicked);
          $('a', tag).mouseover(_this.toggleCloseColor);
          $('a', tag).mouseout(_this.toggleCloseColor);
          $('span', tag).mouseover(function() {
            return tag.popover('show');
          });
          $('span', tag).mouseout(function() {
            return tag.popover('hide');
          });
          return tagList.append(tag);
        });
        return _this.adjustInputPosition();
      };
      this.formatTag = function(i, tag) {
        return "<div class='tag label btn-info' rel='popover' data-placement='bottom' data-content='content' data-original-title='" + tag + "'><span>" + tag + "</span><a> <i class='icon-remove-sign icon-white'></i></a></div>";
      };
      this.addDocumentListeners = function() {
        return $(document).mouseup(function(e) {
          var container;
          container = $('.tags-suggestion-list', _this.$element);
          if (container.has(e.target).length === 0) {
            return _this.hideSuggestions();
          }
        });
      };
      this.init = function() {
        this.tagData = $('.tag-data', this.$element).html();
        this.tagsArray = this.tagData.split(',');
        this.input = $("<input type='text' class='tags-input'>");
        this.input.keydown(this.keyDownHandler);
        this.input.keyup(this.keyUpHandler);
        this.$element.append(this.input);
        this.$suggestionList = $('<ul class="tags-suggestion-list dropdown-menu"></ul>');
        this.$element.append(this.$suggestionList);
        this.renderTags(this.tagsArray);
        return this.addDocumentListeners();
      };
      this.init();
      return this;
    };
    return $.fn.tags = function(options) {
      return this.each(function() {
        var tags;
        return tags = new $.tags(this, options);
      });
    };
  });

}).call(this);
